import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from '@/providers/AuthProvider'
import { Toaster } from 'react-hot-toast';
import RegisterModal from '@/components/modals/RegisterModal'
import LoginModal from '@/components/modals/LoginModal'
import EditModal from '@/components/modals/EditModal';
import Layout from '@/components/Layout';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Toaster />
        <RegisterModal />
        <LoginModal />
        <EditModal />
        <Layout>
          {children}
        </Layout>

      </body>
    </html>
  )
}
